version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: pdmashkov
      POSTGRES_PASSWORD: aksldklasd89239
      POSTGRES_DB: app
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata